version: '3.4'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile_db
    environment:
      # TODO CHANGE PASSWORD LATER or use .env file for password
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=sa
      - POSTGRES_DB=notas
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pg_admin:/var/lib/pgadmin

  backend:
    container_name: backend
    image: backend
    restart: on-failure
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - xml:/app/xml
      # - ./xml:/app/xml
      - alembic:/app/alembic
      - celery:/app/celery
      - ./certificado:/app/certificado
    depends_on:
      - db
      - rabbit
    ports:
      - "5000:5000"

  rabbit:
    container_name: rabbit
    hostname: 'rabbitmq'
    image: rabbitmq
    restart: always
    # ports:
    #   - "6000:6000"
    volumes:
      - mq_data:/var/lib/rabbitmq

volumes:
  xml:
  celery:
  alembic:
  db_data:
  pg_admin:
  mq_data:


